### ISSUE TITLE
getting cause not found

### ISSUE THREAD

**Issue by spaceleap254** [adefokun/Facebook-Profile-Picture-Filter#1]
Hi

I installed  your script on my webserver but all i could get was cause not found line...
I have done all that the read.me file has said but i still cant get the application to work

**Comment by adefokun** [comment]
Can you share how you defined your causes and the link you are using to access the cause?

**Comment by spaceleap254** [comment]
Hi adefokun,

I left the one you had used i.e 
```
$causes = array(
	'quebec' => array('size'=>600, 'opacity' => 60, 'name' => 'flag_quebec', 'image' => 'flag_quebec.png', 'hash' => '#Pray4Quebec', 'title'=>'Pray for Quebec','button'=>'Post to timeline and then set as profile picture', 'contact'=>'postmediapr@gmail.com')
);
```

as for the link i am using ...i have no idea ....

Help me understand this please

**Comment by adefokun** [comment]
Ok, so you enter something like http://filter.i.ng/development/?causeID=quebec

That is a live test of the code.

**Comment by spaceleap254** [comment]
ok let me try that and see how it goes..

**Comment by spaceleap254** [comment]
Hey adefokun, it actually worked ..i had not understood what you meant by access to a filter cause page...Thanks 5 star app...

**Comment by adefokun** [comment]
Oh, good to know, and thanks, this thread will help others understand better. Please feel free to recommend.

**Comment by spaceleap254** [comment]
I will recommend most definitely..
